version: '3'
services:
  backend:
    container_name: backend
    command: ./bin/docker/start
    build: .
    volumes:
      - .:/app
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: postgres://postgres:@ccdb:5433/castcallasia_development

  ccdb:
    container_name: ccdb
    image: postgres:11
    command: -p 5433
    restart: always
    ports:
      - 5433:5433
